version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery_worker

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.main.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.main.celery_app beat --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  db_data:
